name: flutter_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_dotenv:
  android_id:
  device_info_plus:
  shared_preferences:

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/default_poster.jpg

  fonts:
    - family: Catamaran
      fonts:
        - asset: assets/fonts/Catamaran-Regular.ttf
        - asset: assets/fonts/Catamaran-Bold.ttf
          weight: 700
        - asset: assets/fonts/Catamaran-Medium.ttf
          weight: 500
